workflows:
  ios-html-app:
    name: Build iOS IPA
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - name: Install Dependencies and Sync Capacitor
        script: |
          npm install
          npx cap sync ios
          
      - name: Capacitor Native Build iOS
        script: |
          # مسحنا الـ --no-open الرخمة
          npx cap build ios
          
      - name: Package IPA
        script: |
          cd ios/App/DerivedData/*
          cd Build/Products/Debug-iphoneos
          mkdir -p Payload
          cp -R App.app Payload/
          zip -r $CM_BUILD_DIR/FinanceOS.ipa Payload
    artifacts:
      - $CM_BUILD_DIR/*.ipa